name: Gatling Performance Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Run Gatling tests
        run: mvn gatling:test -Dgatling.runMultipleSimulations=true

      - name: Upload Gatling reports
        uses: actions/upload-artifact@v4
        with:
          name: gatling-reports
          path: target/gatling